### PR TITLE
Don't repeatedly store methods from other modules

### PR DESCRIPTION
**Pull request by ZacLN**
Where functions are overloaded by a package this PR only stores methods associated with the package (before we would duplicate method stores for all methods - when things like `+` are extended this is significantly costly).

Note: Would require changes to StaticLint/LanguageServer logic

### CODE REVIEW

**Comment by davidanthoff** [comment]
I think we should merge this soon, and then tag v3.0.0 and start to fix the integration on the LS side, right? I'm waiting with tagging v3.0.0, though, because this PR here seems breaking, right?

**Comment by ZacLN** [comment]
This requires more of a think (it would slow down reference resolution significantly in StaticLint). Not sure it's breaking really but I've modified the PR so that there's no change to package caches but it still makes the internal changes (so you can tag a release).

**Comment by davidanthoff** [comment]
Ok, so I should tag now, without merging this, right?

**Comment by ZacLN** [comment]
No, lets merge it

**Pull request merged**
