### PR TITLE
comment out disabled code blocks

### PR DESCRIPTION
**Pull request by ZacLN**
`Core.Compiler.Params` doesn't exist on Julia 1.6

### CODE REVIEW

**Comment by pfitzseb** [comment]
@aviatesk has a fix for that at https://github.com/JunoLab/Atom.jl/pull/335  :)

**Comment by aviatesk** [comment]
is this used somewhere ? I think I can fix that though.

**Comment by pfitzseb** [comment]
Well,
https://github.com/julia-vscode/SymbolServer.jl/pull/165/files#diff-6a3b27e5bfe405fa75cb4196464e0adcL114

**Comment by ZacLN** [comment]
It's in the title!

**Comment by davidanthoff** [comment]
:) True, but who reads ;)

**Pull request merged**
