### PR TITLE
Fix usage of Pkg internals for Julia >= 1.6.2, fixes #224.

### LINKED ISSUE #224: Small change in Pkg internals in 1.6.2.
To handle the upcoming new 1.7 manifest format in 1.6, a backport was made to Pkg that slightly changed the internals.
This caused the tests here to error. The error can be seen in https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/6d74a23_vs_dd12291/SymbolServer.1.6.2-pre-257e784638.log.

It should be quite easy to workaround.

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Ah, of course: #228

I think this PR fixes usage of `ctx.env.manifest` in some more places though? Maybe not.

**Comment by pfitzseb** [comment]
I'd be happy to go with this if you fix the 1.0 test failure.

**Comment by fredrikekre** [comment]
SymbolServer segfaults for me (but then passes tests...) on Julia 1.0.

Specifically:
```
signal (15): Terminated
in expression starting at /home/fredrik/dev/SymbolServer/src/utils.jl:460
apply_cl at /buildworker/worker/package_linux64/build/src/flisp/flisp.c:1678
do_trycatch at /buildworker/worker/package_linux64/build/src/flisp/flisp.c:898
apply_cl at /buildworker/worker/package_linux64/build/src/flisp/flisp.c:1806
_applyn at /buildworker/worker/package_linux64/build/src/flisp/flisp.c:682
fl_applyn at /buildworker/worker/package_linux64/build/src/flisp/flisp.c:722
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:827
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:839
```
so looks like something in https://github.com/julia-vscode/SymbolServer.jl/blob/488bcb42d28d0201126931e2cd6b63ec1d93d8db/src/utils.jl#L430

**Comment by fredrikekre** [comment]
That also happens on SymbolServer master and on CI https://github.com/julia-vscode/SymbolServer.jl/pull/229/checks?check_run_id=3085321049#step:5:16 so probably not because of this PR?

**Review by pfitzseb — APPROVED** [review]

**Comment by ZacLN** [comment]
This seems to break symbolserver on my machine:
```julia
ERROR: type Dict has no field deps
Stacktrace:
 [1] getproperty(x::Dict{Base.UUID, Pkg.Types.PackageEntry}, f::Symbol)
   @ Base ./Base.jl:33
 [2] read_manifest(manifest_filename::String)
   @ SymbolServer ~/.vscode/extensions/julialang.language-julia-insider-1.2.8/scripts/packages/SymbolServer/src/utils.jl:32
 [3] getstore(ssi::SymbolServerInstance, environment_path::String, progress_callback::LanguageServer.var"#93#95"{LanguageServerInstance}, error_handler::var"#3#4"; download::Bool)
   @ SymbolServer ~/.vscode/extensions/julialang.language-julia-insider-1.2.8/scripts/packages/SymbolServer/src/SymbolServer.jl:33
 [4] macro expansion
   @ ~/.vscode/extensions/julialang.language-julia-insider-1.2.8/scripts/packages/LanguageServer/src/languageserverinstance.jl:182 [inlined]
 [5] (::LanguageServer.var"#92#94"{LanguageServerInstance})()
   @ LanguageServer ./task.jl:411
```

**Comment by fredrikekre** [comment]
Julia version?

**Comment by ZacLN** [comment]
1.7.0-DEV.922

**Comment by fredrikekre** [comment]
Perhaps that is some intermediate version that doesn't have the Pkg updates. Do you also get it with a 1.7 beta?

**Pull request merged**
