### PR TITLE
show method locations

### PR DESCRIPTION
**Pull request by aviatesk**
make it more consistent with Base's print:
```julia
Base.bitshow is a Function.

  # 2 methods for generic function "bitshow":
  [1] bitshow(io::IO, B::BitArray) in Base at show.jl:2256
  [2] bitshow(B::BitArray) in Base at show.jl:2265
```

### CODE REVIEW

**Comment by pfitzseb** [comment]
We should be able to convert those paths into clickable links, no? This is interpreted as markdown by VSCode after all.

**Comment by aviatesk** [comment]
no, I tried that at first, but LSP doesn't support `MarkdownString`, which can make links to [invoke vscode commands](https://code.visualstudio.com/api/references/vscode-api#MarkdownString):

It actually only supports `MarkedString` and `MarkupContent` currently: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_hover

**Comment by pfitzseb** [comment]
[Argh...](https://code.visualstudio.com/api/references/vscode-api#MarkedString)

So a normal markdown link like `[show.jl:2256](~/blah/show.jl:2256)` doesn't work?

**Comment by aviatesk** [comment]
ops, vscode seems to automatically handles those links (i.e. open editors in vscode).
Will try to improve.

**Comment by aviatesk** [comment]
But making those links should be done in LangaugeServer.jl side, so I think this PR can be merged as is.

**Pull request merged**
