### PR TITLE
Async citests

### PR DESCRIPTION
**Pull request by ZacLN**
Testing

### CODE REVIEW

**Comment by ZacLN** [comment]
@davidanthoff, this should fix the fiddly compat issues with v1.0- but tests seem to hang indefinitely at the `take!` call in the tests, not sure

**Comment by davidanthoff** [comment]
I added code that shows exceptions in the async task (instead of just having them disappear in the nothing), I think that should help us pin down what is going on. I think there is something that we expect a UUID but get a string...

**Comment by davidanthoff** [comment]
I fixed two more bugs on Julia 1.0, but now have to run. But there should be proper error output at this point that makes it fairly straightforward to find the right fix.

**Comment by ZacLN** [comment]
Tests should pass but Base64 doesn't seem to get pulled in on v1.0- ?

**Comment by davidanthoff** [comment]
Well, we're getting close :) Something wrong on Julia 1.1 only now?

**Comment by ZacLN** [comment]
It's fixed (locally, tests running now) but mostly be eliding the issue, its not clear to me how important the cache naming.

**Comment by davidanthoff** [comment]
I think (hope) that https://github.com/julia-vscode/SymbolServer.jl/pull/77/commits/18946b1b671691c2725b2eee24bf8403a2b782e7 will fix this properly on all versions of Julia. Let's see what CI says :)

**Comment by ZacLN** [comment]
Well done, that was pretty painful getting that to work!

**Comment by davidanthoff** [comment]
DONE! I'll merge, ok?

**Pull request merged**
